version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - senaycasino-network

  m306-mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: RohrKabel06
      MONGO_INITDB_DATABASE: senaycasino
    volumes:
      - mongodb-data:/data/db
      - ./mongodb/init:/docker-entrypoint-initdb.d
    networks:
      - senaycasino-network

volumes:
  mongodb-data:

networks:
  senaycasino-network:
    driver: bridge